### ISSUE TITLE
SystemError: GetTempFileName

### ISSUE THREAD

**Issue by vbaidin** [sambitdash/PDFIO.jl#87] opened 2020-03-19 17:43 UTC
I read a lot of pdf documents. 
After around 20-36 I have this error: SystemError: GetTempFileName, when I try to get page by it's number. 
After reopening Julia, the same pdf file opens correctly.

**Comment by sambitdash** [comment] 2020-03-19 17:52
Please provide complete stack trace of the error or isolated file where you are observing this issue. Hard to guess the reason of failure otherwise.

**Comment by vbaidin** [comment] 2020-03-19 18:03
> Please provide complete stack trace of the error or isolated file where you are observing this issue. Hard to guess the reason of failure otherwise.

it's hard to replicate. 
I have a folder with 100 pdf files. Each file is around 800-900 pages. Everything is work good, until I have read around 30files. 
So I think you have some problems with temporary files. Maybe it isn't deleted?

**Comment by sambitdash** [comment] 2020-03-20 04:32
@vbaidin from your previous comment, I do not get enough information to reproduce the issue nor have enough resources to replicate your use case. I can see you have some conjecture based on certain observations. If you can establish it with a code snippet with code suggestions we will be happy to take the PR.

**Comment by vbaidin** [comment] 2020-03-20 14:24
> @vbaidin from your previous comment, I do not get enough information to reproduce the issue nor have enough resources to replicate your use case. I can see you have some conjecture based on certain observations. If you can establish it with a code snippet with code suggestions we will be happy to take the PR.

Thank you for your replay. As I mentioned, I can't reproduce it, since it happened only after I have worked with 30 pdf (1000 pages for file). 

I hope. I find the error. I didn't close the document pdDocClose(doc_pdf), so it was my fault. I am sorry

**Comment by sambitdash** [comment] 2020-03-20 14:31
@vbaidin if you didn't close opened PDF files, it's only logical to expect all the temporary file handles will be exhausted. With that information known, I will close the issue. If the issue persists even after closeing the files you can reopen the issue.

**Closed by sambitdash** 2020-03-20 14:31 UTC
