### ISSUE TITLE
Extract all Text Objects

### ISSUE THREAD

**Issue by Banguiskode** [sambitdash/PDFIO.jl#83] opened 2019-12-22 09:38 UTC
Hi !
First of all, thank you for this great tool.
Let me ask you a question:
I would like to be able to extract a table (or a list) containing the text objects with their properties, is that possible?
Thanks

**Comment by sambitdash** [comment] 2019-12-22 13:58
@Banguiskode thank you for your interest in the library. Your expectations are captured as enhancements #2, #7, #11 and #17. 

PDF as a specification does not have any simple mechanism of specifying tabular structures as tables unless you post process the text positions extracted from the PDF files. While the API does not provided a very explicit API for the same of `pdPageEvaluate` can be extended to extract the text data and their positions. As part of tagged specification PDF supports specifying the tabular structure representations but a very small portion of the PDF files available in the market actually implement those specifications to a great extent. If you will like to contribute to any parts of PDFIO by implementing any of the features, we will be happy to accept PRs. 

Since, the intent of the issue is already captured as part of other issues, I will close the issue with this comment.

**Closed by sambitdash** 2019-12-22 13:58 UTC

**Comment by Banguiskode** [comment] 2019-12-22 16:07
Thank you very much for your answer !
